# Generated by Django 4.2.2 on 2023-06-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('basic_user', 'Basic'), ('reporter', 'Reporter'), ('staff_admin', 'Staff admin'), ('super_admin', 'Super Admin')], max_length=20, null=True),
        ),
    ]
