# Generated by Django 4.2.2 on 2023-06-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('basic_user', 'Basic'), ('reporter', 'Reporter'), ('editor', 'Editor'), ('staff', 'Staff'), ('super_admin', 'Super Admin')], max_length=20, null=True),
        ),
    ]
