# Generated by Django 4.2.2 on 2023-06-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('body', models.TextField(max_length=9999)),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('news', 'חדשות'), ('sport', 'ספורט'), ('television', 'טלויזיה'), ('economy', 'כלכלה'), ('health', 'בריאות'), ('worldwide', 'עולם'), ('fasion', 'אופנה'), ('digital', 'דיגיטל')], max_length=20)),
            ],
        ),
    ]
