# Generated by Django 4.2.2 on 2023-06-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
