# Generated by Django 4.2.2 on 2023-06-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_posts_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
